---
# File names that will be looked for in the templates directory of the role that includes this role
ipv4_template_file: etc/iptables/rules.v4
ipv6_template_file: etc/iptables/rules.v6
nftables_template_file: etc/nftables.conf

# Firewall config file to update sysctl values
# Changes this variable to custom file path to use custom sysctl values.
firewall_config_file: fw.conf

firewall_allow_routing: "{{ allow_routing | default(true) }}" # Allow routing between interfaces
mode: nftables # Can iptables or nftables
