# Using startup-script since not all images have cloud-init pre-installed
startup-script: |
  #!/bin/bash

  cat <<'EOF' >{{ machine_operations_google_temp_sshd_config_path }}
  PermitRootLogin yes
  PasswordAuthentication yes
  MaxAuthTries 30
  EOF
  systemctl restart ssh
  # This is a temporary password for the root user, which will be changed as soon as the accounts role is reached.
  echo root:{{ template_password }} | chpasswd

  # Fixing any potential package issues
  apt-get update --fix-missing
  apt-get --fix-broken install -y

  # Needed during os_configuration role
  apt-get install locales -y
