---
- name: Updating Pacman packages...
  community.general.pacman:
    update_cache: true
    upgrade: true
  register: pacman_update

- name: Including restore Python tasks... # noqa: no-handler
  ansible.builtin.include_tasks: restore_python.yml
  when: pacman_update.changed
