---
- name: Updating all packages...
  community.general.pkgng:
    name: "*"
    state: latest # Latest is used in order to perform a full upgrade
    autoremove: true
  register: pkgng_update

- name: Including restore Python tasks... # noqa: no-handler
  ansible.builtin.include_tasks: restore_python.yml
  when: pkgng_update.changed

- name: Rebooting if required after package updates... # noqa: no-handler
  ansible.builtin.reboot:
  when: updates_freebsd_reboot_after_updates | bool
