---
- name: Updating MacOS...
  ansible.builtin.raw: softwareupdate --install --all --agree-to-license --restart
  register: macos_update_result
  changed_when: true
  # There's no way to run raw module asynchronously, so we need to handle unreachable errors
  ignore_unreachable: true

- name: Trying to recover from unreachable error...
  when:
    - macos_update_result.unreachable is defined
    - macos_update_result.unreachable
  block:
    - name: Setting rescue loop count...
      ansible.builtin.set_fact:
        updates_rescue_loop_count: "{{ updates_rescue_loop_count | default(0) | int + 1 }}"

    - name: MACOS UPDATE ERROR
      ansible.builtin.fail:
        msg: |
          MacOS failed to install updates most likely because of a connection timeout.
          Check that the host is up and running and try again.
      when: updates_rescue_loop_count | int > 3

    # In some cases, MacOS update process can cause the machine to become temporarily unreachable.
    # For those cases will try to use the Hypervisor to power cycle the machine and wait for it to come back up.
    - name: Shutting down {{ custom_vm_name | default(vm_name) }} VM...
      ansible.builtin.include_role:
        name: nova.core.powerstate
      vars:
        powerstate_agent_info_timeout: 600
        shutdown: true

    - name: Starting {{ custom_vm_name | default(vm_name) }} VM...
      ansible.builtin.include_role:
        name: nova.core.powerstate
      vars:
        poweron: true

    - name: Waiting until ssh is up for {{ inventory_hostname }}...
      ansible.builtin.wait_for:
        host: "{{ ansible_host }}"
        port: 22
        state: started
        timeout: 300
      delegate_to: localhost
      become: false

    - name: Re-including MacOS tasks...
      ansible.builtin.include_tasks: macos.yml
