---
- name: Updating {{ inventory_hostname }}...
  ansible.builtin.command: opnsense-update -bkp
  register: opnsense_update
  changed_when: opnsense_update.stdout is search("Installing.*")
  when: ansible_network_os | default('') == "opnsense"

- name: Updating {{ inventory_hostname }}...
  ansible.builtin.command: pfSense-upgrade -d -y
  register: pfsense_update
  changed_when: pfsense_update.stdout is search("Installing.*")
  when: ansible_network_os | default('') == "pfsense"

- name: Including restore Python tasks... # noqa: no-handler
  ansible.builtin.include_tasks: restore_python.yml
  when: opnsense_update.changed or pfsense_update.changed

- name: Upgrading {{ inventory_hostname }}...
  ansible.builtin.command: opnsense-update -u
  register: opnsense_upgrade
  changed_when: opnsense_upgrade.stdout is search("Please reboot.*")
  failed_when:
    - opnsense_upgrade.rc != 0
    - opnsense_upgrade.stdout is not search("No known packages set to fetch was specified.")
  when:
    - ansible_network_os | default('') == "opnsense"
    - updates_opnsense_upgrade

- name: Rebooting and re-including updates tasks...
  when: ("Please reboot." in opnsense_update.stdout_lines | default(''))
    or ("Please reboot." in opnsense_upgrade.stdout_lines | default(''))
    or ("Please reboot." in pfsense_update.stdout_lines | default(''))
  block:
    - name: Rebooting...
      ansible.builtin.reboot:

    - name: Re-including updates tasks in case there are more updates available...
      ansible.builtin.include_tasks: sense.yml
