---
- name: Configuring netplan on Proxmox VM...
  become: false
  delegate_to: localhost
  block:
    - name: Templating netplan configuration files...
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "0644"
        lstrip_blocks: true
      loop_control:
        label: "{{ item.src }}"
      loop:
        - src: 70-persistent-net.rules
          dest: /tmp/{{ project_fullname | default('') }}_{{ inventory_hostname }}_70-persistent-net.rules
        - src: netplan.yml
          dest: /tmp/{{ project_fullname | default('') }}_{{ inventory_hostname }}_netplan.yml

    - name: Getting configuration files' contents
      ansible.builtin.slurp:
        path: "{{ item }}"
      register: file_contents
      loop:
        - /tmp/{{ project_fullname | default('') }}_{{ inventory_hostname }}_70-persistent-net.rules
        - /tmp/{{ project_fullname | default('') }}_{{ inventory_hostname }}_netplan.yml

    - name: Removing any existing netplan configurations...
      ansible.builtin.uri:
        url: "{{ proxmox_api_url }}/nodes/{{ cfg_net_proxmox_node }}/qemu/{{ cfg_net_proxmox_vmid }}/agent/exec"
        headers:
          Authorization: PVEAPIToken={{ proxmox_defaults.api_user }}!{{ proxmox_defaults.api_token_id }}={{ proxmox_defaults.api_token_secret }}
        method: POST
        body:
          command:
            - sh
            - -c
            - "rm -f /etc/netplan/*"
        body_format: json
        validate_certs: "{{ proxmox_defaults.validate_certs }}"
      register: network_config_command

    - name: Including command run check task...
      ansible.builtin.include_tasks: command_run_check.yml

    - name: Writing network configuration to {{ custom_vm_name | default(vm_name) }}...
      ansible.builtin.uri:
        url: "{{ proxmox_api_url }}/nodes/{{ cfg_net_proxmox_node }}/qemu/{{ cfg_net_proxmox_vmid }}/agent/file-write"
        headers:
          Authorization: PVEAPIToken={{ proxmox_defaults.api_user }}!{{ proxmox_defaults.api_token_id }}={{ proxmox_defaults.api_token_secret }}
        method: POST
        body:
          content: "{{ file_contents.results[file_index].content | b64decode }}"
          file: "{{ item }}"
        body_format: json
        validate_certs: "{{ proxmox_defaults.validate_certs }}"
      register: network_config_command
      loop_control:
        index_var: file_index
      loop:
        - /etc/udev/rules.d/70-persistent-net.rules
        - /etc/netplan/01-netcfg.yaml

    - name: Applying netplan...
      ansible.builtin.uri:
        url: "{{ proxmox_api_url }}/nodes/{{ cfg_net_proxmox_node }}/qemu/{{ cfg_net_proxmox_vmid }}/agent/exec"
        headers:
          Authorization: PVEAPIToken={{ proxmox_defaults.api_user }}!{{ proxmox_defaults.api_token_id }}={{ proxmox_defaults.api_token_secret }}
        method: POST
        body:
          command:
            - sh
            - -c
            # 3x netplan apply is required for Ubuntu Desktop versions otherwise the network configuration doesn't get applied correctly for some reason
            # Doing that is still cheaper than a single reboot
            - "chmod 600 /etc/netplan/01-netcfg.yaml && netplan apply && netplan apply && netplan apply"
        body_format: json
        validate_certs: "{{ proxmox_defaults.validate_certs }}"
      register: network_config_command

    - name: Including command run check task...
      ansible.builtin.include_tasks: command_run_check.yml

  rescue:
    - name: NETWORK CONFIGURATION ERROR
      ansible.builtin.fail:
        msg: |
          Network configuration has failed {{ configure_networking_rescue_count | default(0) }} times.
          Check the errors above and {{ inventory_hostname }} host logs for more details.
      when: configure_networking_rescue_count | default(0) | int == 3

    - name: Setting rescue loop count...
      ansible.builtin.set_fact:
        configure_networking_rescue_count: "{{ configure_networking_rescue_count | default(0) | int + 1 }}"

    - name: Re-including vSphere network configuration tasks...
      ansible.builtin.include_tasks: main.yml
