---
# Systems needs to be up to date before installing Docker
# Otherwise, Docker installation may fail due to outdated dependencies
- name: Including nova.core.updates role...
  ansible.builtin.include_role:
    name: nova.core.updates

# Required for latest Docker versions on Arch Linux
- name: Enabling IP forwarding...
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: 1
    sysctl_file: /etc/sysctl.d/99-ip_forwarding.conf
    state: present
    reload: true
  loop:
    - net.ipv4.ip_forward
    - net.ipv6.conf.all.forwarding

- name: Installing Docker and requirements...
  ansible.builtin.package:
    name:
      - docker
      - docker-buildx
      - docker-compose
      - python-requests
    state: present
  register: docker_install

# Reboot is required immediately after Docker installation
- name: Rebooting... # noqa: no-handler
  ansible.builtin.reboot:
  when: docker_install.changed
