---
- name: Installing Docker on Debian based OS...
  when: ansible_facts.distribution not in docker_non_default_debian_os_list
  block:
    - name: Downloading Docker repo key for {{ ansible_facts.distribution }}...
      ansible.builtin.get_url:
        url: "{{ docker_apt_proxy | lower }}/gpg"
        dest: /etc/apt/trusted.gpg.d/docker.asc
        mode: "0644"
        timeout: 60

    - name: Adding Docker repository for {{ ansible_facts.distribution }}...
      ansible.builtin.deb822_repository:
        name: docker
        types: [deb]
        uris: "{{ docker_apt_proxy | lower }}"
        suites: ["{{ ansible_facts.distribution_release | lower }}"]
        components: [stable]
        signed_by: /etc/apt/trusted.gpg.d/docker.asc

- name: Removing legacy Docker repository...
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/docker.list
    state: absent

- name: Installing Docker and requirements...
  ansible.builtin.apt:
    name:
      - containerd.io
      - docker-ce-cli{{ '=5:' + docker_engine_version | string + '*' if docker_engine_version != {} else '' }}
      - docker-ce{{ '=5:' + docker_engine_version | string + '*' if docker_engine_version != {} else '' }}
      - docker-compose-plugin
      - python3-docker
      - python3-jsondiff
      - python3-pip
      - python3-requests
      - python3-setuptools
      - python3-wheel
      - python3-yaml
    state: present
    allow_downgrade: true
    update_cache: true

# This is to avoid updating Docker with apt upgrade if a specific version is set
- name: "{{ 'Locking' if docker_engine_version != {} else 'Unlocking' }} Docker engine version..."
  ansible.builtin.dpkg_selections:
    name: "{{ docker_package }}"
    selection: "{{ 'hold' if docker_engine_version != {} else 'install' }}"
  loop_control:
    loop_var: docker_package
  loop:
    - docker-ce-cli
    - docker-ce
  register: docker_dpkg_lock

- name: Updating Docker packages after unlock... # noqa: package-latest
  ansible.builtin.apt:
    name:
      - docker-ce-cli
      - docker-ce
    state: latest
    update_cache: true
  when:
    - docker_engine_version == {}
    - docker_dpkg_lock.changed
