---
- name: Downloading Docker repo key for {{ ansible_facts.distribution }}...
  ansible.builtin.get_url:
    url: "{{ docker_apt_proxy | lower }}/gpg"
    dest: /etc/apt/trusted.gpg.d/docker.asc
    mode: "0644"
    timeout: 60
  vars:
    # Overriding ansible_facts.distribution and ansible_facts.distribution_release to match Debian
    ansible_facts:
      distribution_release: trixie
      distribution: debian

- name: Adding Docker repository for {{ ansible_facts.distribution }}...
  ansible.builtin.deb822_repository:
    name: docker
    types: [deb]
    uris: "{{ docker_apt_proxy | lower }}"
    suites: ["{{ ansible_facts.distribution_release | lower }}"]
    components: [stable]
    signed_by: /etc/apt/trusted.gpg.d/docker.asc
  vars:
    # Overriding ansible_facts.distribution and ansible_facts.distribution_release to match Debian
    ansible_facts:
      distribution_release: trixie
      distribution: debian
