---
- name: Including Docker installation tasks on Windows...
  ansible.builtin.include_tasks: windows.yml
  when: ansible_facts.os_family | default('') == "Windows"

- name: Including Debian based OS requirements tasks...
  ansible.builtin.include_tasks: debian_os_requirements.yml
  when: ansible_facts.os_family | default('') == "Debian"

# This needs to be separate for the ansible_facts overrides to work correctly
- name: Including non-default Debian based OS repo tasks...
  ansible.builtin.include_tasks: debian_os_non_default.yml
  when: ansible_facts.distribution | default('') in docker_non_default_debian_os_list

- name: Including Docker installation tasks on Debian based Linux...
  ansible.builtin.include_tasks: debian_os_default.yml
  when: ansible_facts.os_family | default('') == "Debian"

- name: Including Docker installation tasks on Archlinux...
  ansible.builtin.include_tasks: archlinux.yml
  when: ansible_facts.os_family | default('') == "Archlinux"

- name: Including Docker installation tasks on Fedora...
  ansible.builtin.include_tasks: fedora.yml
  when: ansible_facts.distribution | default('') == "Fedora"

- name: Including Docker installation tasks on AlmaLinux or RHEL...
  ansible.builtin.include_tasks: redhat.yml
  when: ansible_facts.distribution | default('') in ["AlmaLinux", "RedHat"]

- name: Including Docker installation tasks on Alpine...
  ansible.builtin.include_tasks: alpine.yml
  when: ansible_facts.distribution | default('') == "Alpine"

- name: Including Linux specific Docker configuration tasks...
  ansible.builtin.include_tasks: linux.yml
  when: ansible_facts.system | default('') == "Linux"
