---
- name: Removing {{ custom_vm_name | default(vm_name) }} VM...
  when: orchard_vm_exists | default(false) # Only remove if the VM exists
  become: false
  delegate_to: localhost
  block:
    - name: NO UNDEPLOY
      ansible.builtin.fail:
        msg: "{{ inventory_hostname }} Has no_undeploy set and won't be removed"
      when: no_undeploy or ['no_undeploy', 'custom_no_undeploy'] | intersect(group_names) | length > 0

    - name: Removing {{ custom_vm_name | default(vm_name) }}...
      ansible.builtin.command: orchard delete vm {{ custom_vm_name | default(vm_name) }}
      changed_when: true

- name: Stopping play...
  ansible.builtin.meta: end_host
  when: deploy_mode == 'undeploy'
