---
- name:
    Connecting as {{ ansible_deployer_username }} to {{ inventory_hostname }} using {{
    ansible_connection | default('ssh') | upper }} over {{ ansible_host }}... # noqa: name[template]
  ansible.builtin.set_fact:
    ansible_user: "{{ ansible_deployer_username }}"
