---
- name: Checking if kali.sources is used...
  ansible.builtin.stat:
    path: /etc/apt/sources.list.d/kali.sources
  register: kali_sources

- name: Configuring kali.sources...
  when: kali_sources.stat.exists
  block:
    - name: Checking if /etc/apt/kali.sources_backup exists...
      ansible.builtin.stat:
        path: /etc/apt/kali.sources_backup
      register: kali_sources_backup

    - name: Backing up existing kali.sources...
      ansible.builtin.copy:
        src: /etc/apt/sources.list.d/kali.sources
        dest: /etc/apt/kali.sources_backup
        remote_src: true
        mode: "0644"
      when: not kali_sources_backup.stat.exists

- name: Configuring sources.list...
  when: not kali_sources.stat.exists
  block:
    - name: Checking if sources.list backup exists...
      ansible.builtin.stat:
        path: /etc/apt/sources.list_backup
      register: apt_backup_file

    - name: Backing up existing sources.list...
      ansible.builtin.copy:
        src: /etc/apt/sources.list
        dest: /etc/apt/sources.list_backup
        remote_src: true
        mode: "0644"
      when: not apt_backup_file.stat.exists

- name: Removing legacy /etc/apt/sources.list file...
  ansible.builtin.file:
    path: /etc/apt/sources.list
    state: absent

- name: Getting {{ inventory_hostname }} architecture...
  ansible.builtin.command: dpkg --print-architecture
  changed_when: false
  register: dpkg_architecture

- name: Adding Kali repository...
  ansible.builtin.deb822_repository:
    name: kali
    architectures:
      - "{{ dpkg_architecture.stdout }}"
    types: [deb]
    uris: "{{ package_mirror_kali_uri.general }}"
    suites: [kali-rolling]
    components: [main contrib non-free non-free-firmware]
    signed_by: /usr/share/keyrings/kali-archive-keyring.gpg
  register: repos_changed

- name: Running apt update... # noqa: no-handler
  ansible.builtin.apt:
    update_cache: true
  retries: 2
  when: repos_changed.changed
