---
- name: Configuring Ubuntu < 24.04 sources.list
  when: ansible_facts.distribution_major_version | int < 24
  block:
    - name: Checking if sources.list backup exists...
      ansible.builtin.stat:
        path: /etc/apt/sources.list_backup
      register: legacy_apt_backup_file

    - name: Backing up existing {{ ansible_facts.distribution_release }} sources.list...
      ansible.builtin.copy:
        src: /etc/apt/sources.list
        dest: /etc/apt/sources.list_backup
        remote_src: true
        mode: "0644"
      when: not legacy_apt_backup_file.stat.exists

    - name: Templating custom ubuntu-sources.list to {{ inventory_hostname }}...
      ansible.builtin.template:
        src: ubuntu-sources.list
        dest: /etc/apt/sources.list
        mode: "0644"
      register: legacy_apt_sources

- name: Configuring Ubuntu 24.04+ sources.list
  when: ansible_facts.distribution_major_version | int >= 24
  block:
    - name: Checking if ubuntu.sources backup exists...
      ansible.builtin.stat:
        path: /etc/apt/ubuntu.sources_backup
      register: apt_backup_file

    - name: Backing up existing {{ ansible_facts.distribution_release }} ubuntu.sources...
      ansible.builtin.copy:
        src: /etc/apt/sources.list.d/ubuntu.sources
        dest: /etc/apt/ubuntu.sources_backup
        remote_src: true
        mode: "0644"
      when: not apt_backup_file.stat.exists

    - name: Templating custom ubuntu-sources.list to {{ inventory_hostname }}...
      ansible.builtin.template:
        src: ubuntu.sources
        dest: /etc/apt/sources.list.d/ubuntu.sources
        mode: "0644"
      register: apt_sources

- name: Running apt update...
  ansible.builtin.apt:
    update_cache: true
  when: legacy_apt_sources.changed | default(false) or apt_sources.changed | default(false)
