---
- name: Checking if ubuntu.sources is used...
  ansible.builtin.stat:
    path: /etc/apt/sources.list.d/ubuntu.sources
  register: ubuntu_sources

- name: Configuring ubuntu.sources...
  when: not ubuntu_sources.stat.exists
  block:
    - name: Checking if sources.list backup exists...
      ansible.builtin.stat:
        path: /etc/apt/sources.list_backup
      register: legacy_apt_backup_file

    - name: Backing up existing {{ ansible_facts.distribution_release }} sources.list...
      ansible.builtin.copy:
        src: /etc/apt/sources.list
        dest: /etc/apt/sources.list_backup
        remote_src: true
        mode: "0644"
      when: not legacy_apt_backup_file.stat.exists

- name: Configuring ubuntu.sources...
  when: ubuntu_sources.stat.exists
  block:
    - name: Checking if ubuntu.sources backup exists...
      ansible.builtin.stat:
        path: /etc/apt/ubuntu.sources_backup
      register: apt_backup_file

    - name: Backing up existing {{ ansible_facts.distribution_release }} ubuntu.sources...
      ansible.builtin.copy:
        src: /etc/apt/sources.list.d/ubuntu.sources
        dest: /etc/apt/ubuntu.sources_backup
        remote_src: true
        mode: "0644"
      when: not apt_backup_file.stat.exists

- name: Removing legacy /etc/apt/sources.list file...
  ansible.builtin.file:
    path: /etc/apt/sources.list
    state: absent

- name: Getting {{ inventory_hostname }} architecture...
  ansible.builtin.command: dpkg --print-architecture
  changed_when: false
  register: dpkg_architecture

- name: Templating ubuntu.sources...
  ansible.builtin.template:
    src: ubuntu.sources
    dest: /etc/apt/sources.list.d/ubuntu.sources
    mode: "0644"
  register: repos_changed

- name: Running apt update... # noqa: no-handler
  ansible.builtin.apt:
    update_cache: true
  retries: 2
  when: repos_changed.changed
