---
- name: Removing persistent iptables...
  ansible.builtin.package:
    name: iptables-persistent
    state: absent

- name: Installing nftables...
  ansible.builtin.package:
    name: nftables
    state: present
    update_cache: true
  notify: reboot_unix

- name: Templating rules...
  ansible.builtin.template:
    src: "{{ nftables_template_file }}"
    dest: /etc/nftables.conf
    lstrip_blocks: true
    mode: "0644"
  register: nftables_rules
  notify: nftables_restart

# This is required to make sure automatic iptables rules used by Docker gets re-populated
- name: Checking if Docker service exists...
  ansible.builtin.systemd:
    name: docker.service
  register: docker_service_exists
  changed_when: nftables_rules.changed
  notify: docker_restart
