---
- name: Including VMTools upgrade policy tasks block...
  become: false
  delegate_to: localhost
  block:
    - name: Looking up the {{ custom_vm_name | default(vm_name) }} VMTools status...
      vmware.vmware.vm_info:
        guest_name: "{{ custom_vm_name | default(vm_name) }}"
        schema: vsphere
      register: vcenter_vmtools_info

    - name: Configuring VM Tools upgrade policy to {{ vmtools_upgrade_policy }}...
      vmware.vmware_rest.vcenter_vm_tools:
        vm: "{{ vcenter_vmtools_info.guests[0]._vimid }}"
        upgrade_policy: "{{ vmtools_upgrade_policy | upper }}"
      # Retries since the REST modules are unstable
      retries: 5
      delay: 2

    - name: Upgrading VMware Tools...
      community.vmware.vmware_guest_tools_upgrade:
        datacenter: "{{ datacenter }}"
        name: "{{ custom_vm_name | default(vm_name) }}"
      when: vcenter_vmtools_info.guests[0].guest.toolsVersionStatus != "guestToolsUnmanaged"
      retries: "{{ (vcenter_vmtools_policy_timeout if vcenter_vmtools_policy_timeout >= 5 else 5) / 5 }}"
      delay: 5

    - name: VMware Tools are managed by the operating system...
      ansible.builtin.debug:
        msg: |
          VMware Tools are managed by the operating system, skipping upgrade.
          Use the operating system package manager to upgrade VMware Tools.
      when: vcenter_vmtools_info.guests[0].guest.toolsVersionStatus == "guestToolsUnmanaged"
