---
- name: Check if previous installation exists
  ansible.builtin.stat:
    path: "{{ providentia_install_dir }}"
  register: providentia_dir

- name: Stop previous installation
  community.docker.docker_compose_v2:
    project_src: "{{ providentia_install_dir }}"
    state: absent
    build: never
    wait: true
  when: providentia_dir.stat.exists

- name: Removing following old installation folders...
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ providentia_install_dir }}"
    - "{{ providentia_install_dir_git }}"

- name: Clone Providentia repo
  ansible.builtin.git:
    accept_hostkey: true
    repo: https://github.com/ClarifiedSecurity/Providentia.git
    dest: "{{ providentia_install_dir }}"
    version: "{{ providentia_deploy_branch }}"
    force: true
    separate_git_dir: "{{ providentia_install_dir_git }}"

- name: Get current git tag # noqa: command-instead-of-module
  ansible.builtin.command:
    cmd: git describe --tags --abbrev=0
    chdir: "{{ providentia_install_dir }}"
  changed_when: false
  register: git_tag

- name: Use latest support files
  ansible.builtin.include_tasks: update_support_files.yml

- name: Parse the semantic version git tag
  ansible.builtin.set_fact:
    providentia_worker_needed: "{{ providentia_version_major | int > 26 and providentia_version_minor | int >= 2 }}"
  vars:
    version_label: "{{ git_tag.stdout }}"
    providentia_version_major: "{{ version_label | regex_search('v?(\\d+)\\.', '\\1') | int }}"
    providentia_version_minor: "{{ version_label | regex_search('\\.(\\d+)\\.', '\\1') | int }}"
    providentia_version_patch: "{{ version_label | regex_search('\\.(\\d+)(?:[-+]|$)', '\\1') | int }}"

- name: Templating configuration
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ providentia_install_dir }}/"
    lstrip_blocks: true
    mode: "0644"
  loop:
    - compose.yaml
    - features.yml
    - .env
    - Makefile

- name: Update version file # noqa: command-instead-of-module
  ansible.builtin.command:
    cmd: git describe --tags >CURRENT_VERSION
    chdir: "{{ providentia_install_dir }}"
  changed_when: false

- name: Include db migration
  ansible.builtin.include_tasks: migrate_db.yml

- name: Start Providentia containers
  community.docker.docker_compose_v2:
    project_src: "{{ providentia_install_dir }}"
    build: always
    state: present
    pull: always
    remove_orphans: true
    wait: true
