---
- name: Shutting {{ custom_vm_name | default(vm_name) }} down...
  vmware.vmware.vm_powerstate:
    name: "{{ custom_vm_name | default(vm_name) }}"
    datacenter: "{{ datacenter }}"
    state: shutdown-guest
  become: false
  delegate_to: localhost
