---
- name: Suspending {{ custom_vm_name | default(vm_name) }}...
  vmware.vmware.vm_powerstate:
    name: "{{ custom_vm_name | default(vm_name) }}"
    datacenter: "{{ datacenter }}"
    state: suspended
  become: false
  delegate_to: localhost
