---
- name: NO UNDEPLOY
  ansible.builtin.fail:
    msg: "{{ inventory_hostname }} Has no_undeploy set and won't be removed"
  when: no_undeploy or ['no_undeploy', 'custom_no_undeploy'] | intersect(group_names) | length > 0

- name: Deleting {{ custom_vm_name | default(vm_name) | replace('_', '-') }}...
  google.cloud.gcp_compute_instance:
    name: "{{ custom_vm_name | default(vm_name) | replace('_', '-') }}"
    zone: "{{ google_cloud_zone }}"
    state: absent
  become: false
  delegate_to: localhost

- name: Deleting a static public IP address for {{ custom_vm_name | default(vm_name) }}...
  google.cloud.gcp_compute_address:
    name: "{{ custom_vm_name | default(vm_name) }}-public-ip"
    region: "{{ google_cloud_region }}"
    state: absent
  become: false
  delegate_to: localhost

- name: Stopping play...
  ansible.builtin.meta: end_host
  when: deploy_mode == 'undeploy'
