---
- name: Setting hostname to {{ hostname }}...
  ansible.builtin.raw: scutil --set {{ item }}
  changed_when: true
  loop:
    - HostName {{ hostname }}
    - LocalHostName {{ hostname }}
    - ComputerName {{ hostname }}

- name: Updating {{ inventory_hostname }} /etc/hosts file with {{ fqdn }} and {{ hostname }}...
  ansible.builtin.raw: |
    line="127.0.1.1 {{ fqdn }} {{ hostname }}"
    file=/etc/hosts
    grep -qxF "$line" $file || echo "$line" >> $file
  changed_when: true
