---
- name: Setting FQDN as hostname...
  vyos.vyos.vyos_config:
    lines:
      - set system host-name {{ fqdn }}
    save: true

- name: Setting NTP...
  vyos.vyos.vyos_config:
    lines:
      - set service ntp server {{ ntp_servers[0] }}
    save: true

- name: Running commands over SSH...
  vars:
    ansible_become: true
    ansible_connection: ansible.builtin.ssh
  block:
    - name: Regenerating machine-id & host ssh keys...
      ansible.builtin.shell: "{{ lookup('template', 'regenerate-machine-id.sh') }}"
      args:
        executable: /bin/bash
      register: regenerate_machine_id
      changed_when: regenerate_machine_id.stdout != "done"

    # This is to avoid ssh connection issues because of the new ssh keys
    - name: Rebooting {{ inventory_hostname }}... # noqa: no-handler
      ansible.builtin.reboot:
      when: regenerate_machine_id.changed
