---
- name: Setting VMware Workstation hosts connection variables...
  ansible.builtin.set_fact:
    ansible_host: "{{ vmware_workstation.host }}"
    ansible_user: "{{ vmware_workstation.user }}"
    ansible_password: "{{ vmware_workstation.password | default(omit) }}"

- name: Setting VMTools to auto update...
  when: os_configuration_vmware_workstation_vmtools_autoupdate
  block:
    # Using lineinfile to check for file changes because it simpler and faster then reading the file and comparing it with the desired state
    - name: Checking VMTools auto-update state for {{ custom_vm_name | default(vm_name) }}...
      ansible.builtin.lineinfile:
        path: "{{ vmware_workstation.local_vmx_path }}"
        regex: tools.upgrade.policy.*
        line: tools.upgrade.policy = "upgradeAtPowerCycle"
        state: present
      register: vmtools_autoupdate

    - name: Configuring VMTools auto-update... # noqa: no-handler
      when: vmtools_autoupdate.changed
      block:
        - name: Getting VMTools current state for {{ custom_vm_name | default(vm_name) }}...
          ansible.builtin.command: vmcli tools query {{ vmware_workstation.local_vmx_path }}
          changed_when: false
          register: vmtools_state

        - name: Upgrading VMTools for {{ custom_vm_name | default(vm_name) }}...
          ansible.builtin.command: vmcli tools upgrade {{ vmware_workstation.local_vmx_path }}
          changed_when: true
          when: not (vmtools_state.stdout is search("versionStatus.*supported_new")) # If a newer version is already installed we don't need to upgrade

        - name: Setting VMTools to upgrade on boot for {{ custom_vm_name | default(vm_name) }}...
          ansible.builtin.command: vmcli configparams setentry tools.upgrade.policy upgradeAtPowerCycle {{ vmware_workstation.local_vmx_path }}
          changed_when: true

    - name: Restoring original connection variables...
      ansible.builtin.set_fact:
        ansible_host: "{{ connection_address }}"
        ansible_user: "{{ ansible_deployer_username }}"
        ansible_password: "{{ ansible_deployer_password | default(omit) }}"
