---
- name: Including VMTools role...
  ansible.builtin.include_role:
    name: nova.core.vcenter_vmtools_policy

- name: Removing extra cdroms...
  when: template_os_configuration_remove_extra_cdroms_on_vsphere
  become: false
  delegate_to: localhost
  block:
    - name: Looking up the {{ custom_vm_name | default(vm_name) }} cdroms...
      vmware.vmware.vm_info:
        guest_name: "{{ custom_vm_name | default(vm_name) }}"
        schema: vsphere
      register: vcenter_vm_info

    - name: Creating a list of all existing devices...
      ansible.builtin.set_fact:
        existing_devices: "{{ vcenter_vm_info.guests[0].config.hardware.device }}"

    - name: Checking if there are multiple cdroms...
      when: existing_devices | selectattr('_vimtype', 'equalto', 'vim.vm.device.VirtualCdrom') | sort(attribute='key') | length > 1
      block:
        - name: Shutting down {{ custom_vm_name | default(vm_name) }} VM...
          ansible.builtin.include_role:
            name: nova.core.powerstate
          vars:
            shutdown: true

        - name: Getting the first existing cdrom controller key...
          ansible.builtin.set_fact:
            primary_cdrom_controller:
              "{{ existing_devices | selectattr('_vimtype', 'equalto', 'vim.vm.device.VirtualCdrom')
              | sort(attribute='key') | map(attribute='controllerKey') | first }}"

        - name: Keeping only the first cdrom...
          vmware.vmware.vm:
            name: "{{ custom_vm_name | default(vm_name) }}"
            cdroms:
              - device_node:
                  # Converting the existing cdrom label to the device device_node required format
                  "{{ (existing_devices | selectattr('key', 'equalto', primary_cdrom_controller) | map(attribute='deviceInfo.label') | first)
                  | regex_replace('^([A-Za-z]+)\\s+(\\d+)$', '\\1(\\2:0)') }}"

        - name: Starting {{ custom_vm_name | default(vm_name) }} VM...
          ansible.builtin.include_role:
            name: nova.core.powerstate
          vars:
            poweron: true
