---
- name: Waiting for Sysprep to finish...
  block:
    - name: Waiting until {{ custom_vm_name | default(vm_name) }} is powered off...
      vmware.vmware.guest_info:
        guest_name: "{{ custom_vm_name | default(vm_name) }}"
      register: vm_tools
      until: vm_tools.guests[0].hw_power_status == "poweredOff"
      retries: "{{ (win_sysprep_timeout if win_sysprep_timeout >= 30 else 30) / 30 }}"
      delay: 30
      become: false
      delegate_to: localhost

  rescue:
    - name: SYSPREP WAIT TIMEOUT
      ansible.builtin.fail:
        msg: |
          Timeout waiting for Sysprep to shut down the VM.
          Check the C:\Windows\System32\Sysprep\Panther\setuperr.log file on the VM for more details.
