---
##########
# Domain #
##########

# Type of Domain Controller role to configure
# Options:
# pdc - Primary Domain Controller the first DC in a new domain
# dc - Backup Domain Controller, secondary (or any next after) DC joining an existing domain)
samba_dc_role: {}

samba_domain_name: "{{ ad_domain_name | default(domain) }}"
samba_domain_netbios: "{{ domain_netbios | default(ad_domain_name.split('.')[0] | upper) }}"
samba_domain_admin_username: "{{ domain_admin_username | default('Administrator') }}"
samba_domain_admin_password: "{{ domain_admin_password | default({}) }}"

# Nr of days after which domain user passwords will expire. Set to 0 to disable password expiry.
samba_domain_disable_password_expiry_days: 0

# Nr of days before how long a user must wait to change their password.
samba_domain_minimum_password_age_days: 0

# The functional level of the domain. This can be set to one of the following values:
# 2000, 2003, 2008, 2008_R2, 2016
# When left empty, the default functional level will be used for the version of Samba being used that's most likely 2008_R2
samba_domain_functional_level: {}

# Enable Samba DC logging in json format in
samba_enable_logging: true
samba_logging_json_path: /var/log/samba/json

#########
# LDAPs #
#########

# Enable or disable LDAPs connections for Samba
# Requires certificate to be pre-installed on the system
samba_ldaps_enable: true

# Path to Root CA file for LDAPs connections
# Can be left empty if it's already in OS trust store
samba_ldaps_ca_file: {}

# Path to LDAPs certificate private key file
samba_ldaps_key_file: /srv/certs/{{ fqdn }}_key.crt

# Path to LDAPs certificate public key file
samba_ldaps_cert_file: /srv/certs/{{ fqdn }}_fullchain.crt

#######
# DNS #
#######

samba_dns_forwarders: "{{ (dns_forwarders6 | default(['2606:4700:4700::1111', '2001:4860:4860::8888'])) + (dns_forwarders | default(['1.1.1.1', '8.8.8.8'])) }}"

# The interface to bind Samba to. This is usually the interface that has the IP address of the machine in the domain.
# Otherwise Samba will bind to all interfaces and can start generating DNS names for localhost and Docker containers which can cause issues
# The default is the egress network interface of the host set it to [] not to bind to any interface and let Samba bind to all interfaces
samba_bind_interfaces:
  - "{{ egress_network_info.nic_name }}"
