---
# Can also be UPGRADE_AT_POWER_CYCLE
vmtools_upgrade_policy: MANUAL

# How long to wait in seconds for VMTools to be running or upgraded before failing the task.
vcenter_vmtools_policy_timeout: 180
