---
# Ignoring symbolic links and only listing user accounts that have a .created file in their home directory, which indicates they were created by this role.
- name: Listing user accounts created with {{ ansible_role_name }}...
  ansible.builtin.raw: |
    for profile in /Users/*; do
      if [[ -f "$profile/.created" && ! -L "$profile" ]]; then
        basename "$profile"
      fi
    done
  register: home_profiles
  changed_when: false

# Filtering out empty lines
- name: Getting profiles not defined in accounts list...
  ansible.builtin.set_fact:
    user_profiles_to_remove:
      "{{ home_profiles.stdout_lines | select('string') | select('regex', '.+')
      | difference(local_accounts_with_password | map(attribute='username')) }}"

- name: Removing stale user accounts and profiles...
  when: user_profiles_to_remove != []
  block:
    - name: Removing following accounts...
      ansible.builtin.raw: |
        pkill -9 -u {{ item }}
        sysadminctl -deleteUser {{ item }}
        # rm -rf /Users/{{ item }}
        # dscl . -delete /Users/{{ item }}
      loop: "{{ user_profiles_to_remove }}"
      changed_when: true

  rescue:
    - name: Handling reboot before removing accounts...
      when: accounts_reboot_before_remove | bool
      block:
        - name: Rebooting
          ansible.builtin.raw: reboot
          changed_when: true
          # Running reboot from ansible.builtin.raw can cause a race condition where the task is marked as failed
          # because the connection is lost before the reboot command completes.
          # To avoid this, we can ignore unreachable hosts after issuing the reboot command.
          ignore_unreachable: true
          when: not darwin_with_python

        - name: Rebooting
          ansible.builtin.reboot:
          when: darwin_with_python

    - name: Removing following accounts...
      ansible.builtin.raw: |
        pkill -9 -u {{ item }}
        sysadminctl -deleteUser {{ item }}
        # rm -rf /Users/{{ item }}
        # dscl . -delete /Users/{{ item }}
      loop: "{{ user_profiles_to_remove }}"
      changed_when: true
